### ISSUE TITLE
Bulk uploads causing resource issues

### ISSUE THREAD

**Issue by mattdebont** [jncc/elasticsearch-lambda-ingester#4]
Bulk uploads have thrown up a few issues with the lambda ingester around reuse of the instances and not properly closing old resources down. Currently we relied on grabage collection to close objects, but we need to specifically close;

- [x] JsonB objects (Ingester.java) (too many objects open)
- [x] Elasticsearch Client objects (ElasticsearchService.java) (too many objects open)

**Comment by mattdebont** [comment]
JsonB objects are now closed when finished using a try (JsonB jsonb = JsonBuilder.create() { .... }

**Comment by mattdebont** [comment]
Elastic search client has been made into a singleton pattern, may still have to come back and revisit this at some point however, but hopefully the singleton pattern will resolve this

**Comment by mattdebont** [comment]
No more problems so far, but haven't got a good way of detecting when this happens beyond monitoring the error queue, which doesn't give the actual error

**Comment by mattdebont** [comment]
Detecting would require a bit of a rework on the lambda client to output the errors somewhere specific or a monitoring system to filter the outputs on the other side (the log groups are 1 per container, and cant be filtered on in a group so difficult to find things)

**Comment by completer** [comment]
(Experimenting with multiple assignees. Matt is the 'primary' assignee but I helped a little bit - unfortunately I can't seem to reflect that in the issue avatar.)
